### ISSUE TITLE
add downsampling filter

### ISSUE THREAD

**Issue by adelavega** [PsychoinformaticsLab/pliers#426]
This should operate on extractor result outputs

**Comment by tyarkoni** [comment]
This may take some work to properly integrate into the `Transformer` hierarchy... Currently every `Transformer` has to take a `Stim` as input, and `ExtractorResult` objects aren't Stims. We have the ER --> `SeriesStim` converter, so we could in principle convert every ER to a series, downsample via the new filter, and then re-aggregate into an ER. But that would be pretty ugly and inefficient. I'm tempted to make this a utility function (e.g., `downsample_results`) rather than a proper `Filter`, at least for now. Or maybe a standalone class that supports the `fit()` interface but doesn't inherit from `Transformer` (that way it should still work in a `Graph`, even if it doesn't have all of the standard magic that applies to `Stim` inputs).

**Comment by adelavega** [comment]
the latter would be more useful, i think. would allow for graphs, which would be a clean consistent specification of the provenance.

**Comment by adelavega** [comment]
Could this be a built-in function of the `Transformer` or `Extractor` class?

**Comment by tyarkoni** [comment]
Theoretically yes, but I think that would be an inefficient way to do it. You'd need to then specify the target sampling rate to each `Transformer` at initialization, and I don't really like the idea of adding even more logic to the output of the `transform()` call before it gets passed to an `ExtractorResult`. A related possibility would be to do it in the `ExtractorResult` itself, but that suffers from similar issues.

I think having a standalone function or a new `Transformer`-like class specifically for this is the way to go. I don't have a strong preference between the two, but if we went with the former, we could potentially add an optional `sampling_rate` argument to the `Graph`, so that it would implicitly invoke the standalone downsampler after the `merge_results` step.

**Comment by adelavega** [comment]
Okay that works for me. I would just like for the last Extractor element in the history to reflect the extractor itself, versus a downsampling operation (makes it easier to track provenance). 

That approach makes sense to me though.

**Comment by tyarkoni** [comment]
We could still potentially update the `ExtractorResults._history` attribute directly from `ExtractorResults.resample()`, though I have mixed feelings, and some fields (e.g., the name of the transformer) would presumably have to be left blank.

**Comment by adelavega** [comment]
That's fine, I'm actually saying I prefer to see the actual extractor as the last element of the history so this works

**Comment by tyarkoni** [comment]
Oh, sorry, I misread. Then yeah, you're all good!

**Comment by adelavega** [comment]
Closed by #430
